<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/08/28 12:55:47

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'dragonfly',
  'name' => 'doctrine',
)),);
